### PR TITLE
Check for Forwarded tag in patch files

### PR DESCRIPTION
**Pull request by mkoncek**
Resolves: #55

### CODE REVIEW

**Review by mizdebsk — CHANGES_REQUESTED** [review]
The output looks wrong. It lists many (all?) patches, even those containing Forwarded: tag

**Comment by mizdebsk** [comment]
The following one-line shell code can be used instead of more complex loop:

    ! grep -L ^Forwarded: patches/*/*.patch | grep .

**Comment by mkoncek** [comment]
Good suggestion.
I believe the previous Check output was actually the complement to the correct set of patches.

**Comment by mizdebsk** [comment]
Why use "if" and not the one-line version?

**Comment by mkoncek** [comment]
Current one-liner does not exit on failure.

**Comment by mizdebsk** [comment]
My version does, see #61 
Closing this one in favor of #61

**Pull request closed without merging**
